#!/usr/bin/env python
#if __name__ == '__main__':
from flask import Flask,request,render_template,redirect
app = Flask(__name__)

dict = {}
@app.route('/userlist')
def userlist():
    user = request.args.get('user')
    password  = request.args.get('pwd')
    fd = file('f.txt', 'a')
    fd.write('%s %s\n' %(user,password)
    fd.close()
    table_str = '<table border="1"><tr><td>user</td><td>password</td><td>option</td><tr>'
    for l in open('f.txt'):
        tmp = l.replace('\n','').split(' ')
        dict[tmp[0]] = tmp[1]
        table_str += '<tr><td>%s</td><td>%s</td><td><a href="/del?username=%s">delect</a></td></tr>'%(tmp[0],tmp[1],tmp[0])
    table_str += '</table>'
    web = ''' 
      <body>

      <form action='/userlist'>
          user:<input name="user" type="text">
          password:<input name="pwd" type="password">
          <input type="submit" value='add'>
      </form>
           %s
     </body>
    ''' % table_str
    return web
@app.route('/del')
def delect():
    for l in open('f.txt'):
        tmp = l.replace('\n','').split(' ')
        dict[tmp[0]] = tmp[1]
    username = request.args.get('user')
    print username
    if username in dict:
        dict.pop(username)
    re_fd = file('f.txt','wb')
    for key in dict:
        re_fd.write('%s %s\n' %(key,dict[key]))
    re_fd.close()
    return redirect('/userlist')     


if __name__ == '__main__':
    app.run(host='0.0.0.0',port=1024,debug=True)
